# Generated by Django 6.0 on 2026-01-02 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Plaintext value (for non-sensitive fields)",
                        null=True,
                    ),
                ),
                (
                    "encrypted_value",
                    models.BinaryField(
                        blank=True,
                        help_text="Encrypted value (for sensitive fields)",
                        null=True,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "field_answers",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="For anonymous/resumable sessions",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "survey_responses",
                "ordering": ["-started_at"],
            },
        ),
    ]
