# Generated by Django 6.0 on 2026-01-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldanswer",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.field",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="last_section",
            field=models.ForeignKey(
                blank=True,
                help_text="For resuming partial responses",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="surveys.section",
            ),
        ),
    ]
