# Generated by Django 6.0 on 2026-01-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0002_initial"),
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user (if logged in)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="fieldanswer",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="submissions.surveyresponse",
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["survey"], name="survey_resp_survey__49b633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["respondent"], name="survey_resp_respond_5f6ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["session_token"], name="survey_resp_session_aa12b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["status"], name="survey_resp_status_e3e571_idx"),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("respondent__isnull", True),
                    ("session_token__isnull", True),
                    _negated=True,
                ),
                name="response_has_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldanswer",
            index=models.Index(
                fields=["response"], name="field_answe_respons_11f611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldanswer",
            index=models.Index(fields=["field"], name="field_answe_field_i_279dc1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fieldanswer",
            unique_together={("response", "field")},
        ),
    ]
