# Generated by Django 6.0 on 2026-01-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
