# Generated by Django 6.0 on 2026-01-05 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_surveyresponse_ip_address_surveyresponse_user_agent"),
        ("surveys", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address invitation was sent to",
                        max_length=254,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the invitation email was sent",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        help_text="User who triggered the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "invitations",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["survey"], name="invitations_survey__e77055_idx"
                    ),
                    models.Index(fields=["email"], name="invitations_email_6e7169_idx"),
                    models.Index(
                        fields=["sent_at"], name="invitations_sent_at_4a9f88_idx"
                    ),
                ],
            },
        ),
    ]
