# Generated by Django 6.0 on 2026-01-02 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("viewed", "Viewed"),
                            ("exported", "Exported"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("survey", "Survey"),
                            ("section", "Section"),
                            ("field", "Field"),
                            ("response", "Response"),
                            ("user", "User"),
                            ("role", "Role"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(help_text="ID of the affected resource"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text='Before/after values for updates. Format: {"before": {...}, "after": {...}}',
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Client user agent", max_length=500
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
