# Generated by Django 6.0 on 2026-01-02 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="If True, value will be encrypted when stored",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration (placeholder, min/max, etc.)",
                    ),
                ),
                (
                    "has_dependencies",
                    models.BooleanField(
                        default=False,
                        help_text="True if this field options depend on another field",
                    ),
                ),
            ],
            options={
                "db_table": "fields",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConditionalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("section", "Section"), ("field", "Field")],
                        max_length=20,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        help_text="ID of the section or field to show/hide"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("greater_than", "Greater Than"),
                            ("less_than", "Less Than"),
                            ("contains", "Contains"),
                            ("in", "In"),
                            ("is_empty", "Is Empty"),
                            ("is_not_empty", "Is Not Empty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Value to compare against (null for is_empty/is_not_empty)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("show", "Show"), ("hide", "Hide")],
                        default="show",
                        max_length=10,
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        help_text="The field whose answer triggers this rule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers_rules",
                        to="surveys.field",
                    ),
                ),
            ],
            options={
                "db_table": "conditional_rules",
            },
        ),
        migrations.CreateModel(
            name="FieldDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_value",
                    models.CharField(
                        help_text="When source field equals this value...",
                        max_length=255,
                    ),
                ),
                (
                    "dependent_options",
                    models.JSONField(
                        help_text='...show these options. Format: [{"label": "...", "value": "..."}]'
                    ),
                ),
                (
                    "dependent_field",
                    models.ForeignKey(
                        help_text="The field whose options change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depends_on_rules",
                        to="surveys.field",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        help_text="The field that triggers the change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls_options_for",
                        to="surveys.field",
                    ),
                ),
            ],
            options={
                "db_table": "field_dependencies",
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.field",
                    ),
                ),
            ],
            options={
                "db_table": "field_options",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="field",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="surveys.section",
            ),
        ),
    ]
