# Generated by Django 6.0 on 2026-01-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="surveys.survey",
            ),
        ),
        migrations.AddIndex(
            model_name="conditionalrule",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="conditional_target__5909b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conditionalrule",
            index=models.Index(
                fields=["source_field"], name="conditional_source__f8ee15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddependency",
            index=models.Index(
                fields=["dependent_field"], name="field_depen_depende_26590a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fielddependency",
            index=models.Index(
                fields=["source_field", "source_value"],
                name="field_depen_source__ee35fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldoption",
            index=models.Index(
                fields=["field", "order"], name="field_optio_field_i_3d5f21_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldoption",
            unique_together={("field", "value")},
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(
                fields=["section", "order"], name="fields_section_55b349_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["status"], name="surveys_status_893a62_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["created_by"], name="surveys_created_6cc90a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["survey", "order"], name="sections_survey__d99547_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("survey", "order")},
        ),
    ]
